args = [
  "-nographic",
  "-machine",
  "virt",
  "-smp",
  "1",
#   "-device",
#   "virtio-blk-device,drive=disk0",
#   "-drive",
#   "id=disk0,if=none,format=raw,file=/home/yanlien/Program/riscv64/axvisor/tmp/images/qemu_aarch64_arceos/rootfs.img",
  "-m",
  "8g",
]
fail_regex = []
success_regex = []
to_bin = true
uefi = false